---
- name: Initialize disk, make dynamic, and format in NTFS
  hosts: all
  gather_facts: true

  vars:
    data_disks:
      - disk_number: 1
        drive_letter: "D:"
        label: data1
      - disk_number: 2
        drive_letter: "E:"
        label: data2
      - disk_number: 3
        drive_letter: "F:"
        label: data3
      - disk_number: 4
        drive_letter: "G:"
        label: data4
      # Add more disks as needed

  tasks:
    - name: Initialize disk using diskpart
      win_shell: |
        $DiskNumber = {{ item.disk_number }}
        $Script = @"
          select disk $DiskNumber
          online disk
          attributes disk clear readonly
        "@
        Add-Content -Path "$env:TEMP\InitializeDiskScript.txt" -Value $Script
        Start-Process -FilePath diskpart.exe -ArgumentList "/s $env:TEMP\InitializeDiskScript.txt" -Wait
      loop: "{{ data_disks }}"

    - name: Convert disk to dynamic using diskpart
      win_shell: |
        $DiskNumber = {{ item.disk_number }}
        $Script = @"
          select disk $DiskNumber
          convert dynamic
        "@
        Add-Content -Path "$env:TEMP\ConvertToDynamicScript.txt" -Value $Script
        Start-Process -FilePath diskpart.exe -ArgumentList "/s $env:TEMP\ConvertToDynamicScript.txt" -Wait
      loop: "{{ data_disks }}"

    - name: Format partition in NTFS using diskpart
      win_shell: |
        $DiskNumber = {{ item.disk_number }}
        $DriveLetter = "{{ item.drive_letter }}"
        $Label = "{{ item.label }}"
        $Script = @"
          select disk $DiskNumber
          clean
          create partition primary
          assign letter=$DriveLetter
          format fs=ntfs label=$Label quick
        "@
        Add-Content -Path "$env:TEMP\FormatDiskScript.txt" -Value $Script
        Start-Process -FilePath diskpart.exe -ArgumentList "/s $env:TEMP\FormatDiskScript.txt" -Wait
      loop: "{{ data_disks }}"
