---
- hosts: all
  gather_facts: true
  tasks:
    - name: Set a custom variable
      set_fact:
        t_morpheus_instance: "{{ morpheus.instance | to_json | safe }}"
 
    - name: Display message
      debug:
        var: t_morpheus_instance

