---
  - name: "extra variable demo"
    hosts: localhost
    connection: local
    vars:
      fruit: "banana"
    tasks:

    - name: "print message"
      ansible.builtin.debug:
        msg: "fruit is {{ fruit }}"
